@appendable
struct LampControl {

    @key uint32 lampID;
    float intensity;
    boolean power;
};

struct CameraControl {

    @key uint32 cameraId;
    boolean	power;
    boolean	light;
    float focus;
    float zoom;

};

struct PanAndTiltControl {

    float x;
    float y;
    float z;
    
};