@appendable
struct LampControlCustom {

    @key uint32 lampID;
    float intensity;
    boolean power;
};

struct CameraControlCustom {

    @key uint32 cameraID;
    boolean	power;
    boolean	light;
    float focus;
    float zoom;

};

struct PanAndTiltControlCustom {

    @key uint32 panandtiltID;
    float x;
    float y;
    float z;
    
};

struct LampControl {

    float intensity[16];
    int16 power;
};

struct CameraControl {

    int16 focus_far;
    int16 focus_near;
    int16 LED;
    int16 power;
    int16 zoom_in;
    int16 zoom_out;

};

struct PanAndTiltControl {

    int16 pan_left;
    int16 pan_right;
    int16 power;
    int16 tilt_down;
    int16 tilt_up;
    
};

struct PanAndTiltPositionSubscriber {

    float pan_one;
    float tilt_one;
    float pan_two;
    float tilt_two;
    float pan_three;
    float tilt_three;
    float pan_four;
    float tilt_four;
    float pan_five;
    float tilt_five;
    float pan_six;
    float tilt_six;
    float pan_seven;
    float tilt_seven;
    float pan_eight;
    float tilt_eight;

};


struct Quaternion {

    float x;
    float y;
    float z;
    float w;
};

struct PanAndTiltPositionPublisher {

    @key uint32 panandtiltID;
    Quaternion angle;

};