@appendable
struct LampControlCustom {

    @key uint32 lampID;
    float intensity;
    boolean power;
};

struct CameraControlCustom {

    @key uint32 cameraId;
    boolean	power;
    boolean	light;
    float focus;
    float zoom;

};

struct PanAndTiltControlCustom {

    float x;
    float y;
    float z;
    
};

struct Power {
    octet CMD;
    octet On;
};

struct LampControl {

    float intensity;
    Power power;
};

struct CameraControl {

    Power focus_far;
    Power focus_near;
    Power LED;
    Power power;
    Power zoom_in;
    Power zoom_out;

};

struct PanAndTiltControl {

    Power pan_left;
    Power pan_right;
    Power power;
    Power tilt_down;
    Power tilt_up;
    
};